name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/photo.jpeg
   - assets/twitter.png
   - assets/telegram.png
   - assets/linkedin.png
   - assets/instagram.png
   - assets/github.png
   - assets\link.png
   - assets\linksvg.svg
   - assets\github.png
   - assets\walletover.png
   - assets\music.png
   - assets\bicycle.png
